"""
Django settings for djangoProject project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-qmonf3&xufd%91m&(l4jl4%7&_w9rq#-&59k9=ye!(3%me5hx-"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'intro',
    'home',
    'student',
    'trainer',
    'userextend',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "djangoProject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'djangoProject.context_processors.get_all_trainers', # imi apeleaza functia get_all_trainers pe orice pagina html
            ],
        },
    },
]

WSGI_APPLICATION = "djangoProject.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Bucharest"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/' # este o setare care specifica URL ul de baza pentru servirea fisierlor din folderul static catre client(browser)
STATICFILES_DIRS = (os.path.join(BASE_DIR), 'static') # este o setare care defineste cai de fisiere (css, js, imagini) pentru aplicatia Djanog
# permite specificarea unor direactoare din static care vor fi servite de Django

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

#MEDIA Files

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

#MEDIA_URL -> ESTE URL DE BAZA CARE VA FI UTILIZAT PENTRU A ACCESA FISIERELE INCARCATE
#MEDIA_ROOT -> este calea absoluta catre folderul in care fisierele media incarcate for fi stocate pe server

# pip install pillow - Pillow este o biblioteca in python folosita/utilizata pentru manipularea imaginilor. Ofera functii pentru
# deschiderea, editarea, salvarea si manipularea imaginilor



LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/' # mentionam prefixul URL-ului unde vrem sa fie redirectionat utilizatorul cand se va loga
LOGOUT_REDIRECT_URL = '/login/' #mentionam prefixul URL-ului unde vrem sa fie redirectionat utilizatorul(catre pagina de login atunci cand se delogheaza)

#SMTP -> SIMPLE MAIL TRANSFER PROTOCOL - protocol pentru a trimite mailuri

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# EMAIL_HOST = 'mail.aplicatiedjango.ro'
# EMAIL_HOST_USER = 'ro45@aplicatiedjango.ro'
# EMAIL_HOST_PASSWORD = 'Django1234!'
# EMAIL_PORT = 587
DEFAULT_FROM_EMAIL = 'ro45@aplicatiedjango.ro'

