# Generated by Django 4.2.3 on 2023-07-31 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0005_alter_student_profile"),
        ("userextend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="student.student",
            ),
        ),
    ]
