# Generated by Django 4.2.3 on 2023-07-31 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userextend", "0002_history_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history",
            name="student",
        ),
    ]
