# Generated by Django 4.2.3 on 2023-07-18 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_student_trainer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
