# Generated by Django 4.2.3 on 2023-07-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_rename_create_at_student_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="profile",
            field=models.ImageField(null=True, upload_to="student_profiles/"),
        ),
    ]
