# Generated by Django 4.2.3 on 2023-07-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_student_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="profile",
            field=models.ImageField(
                blank=True, null=True, upload_to="student_profiles/"
            ),
        ),
    ]
